package configs

/**
 * Created by mingjian.deng on 2020/6/11.
 */
enum class GlobalConfig(name: String) {
    // db config
    ZOPS_DB_URL("ZOPS_DB_URL"),
    ZOPS_DB_USER("ZOPS_DB_USER"),
    ZOPS_DB_PASSWORD("ZOPS_DB_PASSWORD"),
    ZOPS_DB_MAXACTIVE("ZOPS_DB_MAXACTIVE"),
    ZOPS_DB_INITIALSIZE("ZOPS_DB_INITIALSIZE"),
    ZOPS_DB_TIMEBETWEENEVICTIONRUNSMILLS("ZOPS_DB_TIMEBETWEENEVICTIONRUNSMILLS"),

    // mysql config
    ZOPS_MYSQL_HOST("ZOPS_MYSQL_HOST"),
    ZOPS_MYSQL_PORT("ZOPS_MYSQL_PORT"),
    ZOPS_MYSQL_ROOT_PASSWORD("ZOPS_MYSQL_ROOT_PASSWORD"),
    ZOPS_MYSQL_SERVICE_NAME("ZOPS_MYSQL_SERVICE_NAME"),
    ZOPS_SKIP_MIGRATION("ZOPS_SKIP_MIGRATION"),

    // http config
    ZOPS_HTTP_SERVER_IP("ZOPS_HTTP_SERVER_IP"),
    ZOPS_HTTP_SERVER_PORT("ZOPS_HTTP_SERVER_PORT"),
    ZOPS_WEB_SOCKET_PORT("ZOPS_WEB_SOCKET_PORT"),
    ZOPS_DOC_SITE_PORT("ZOPS_DOC_SITE_PORT"),

    // cobbler config
    ZOPS_COBBLER_DEFAULT_SWAP_PARTITION_SIZE("ZOPS_COBBLER_DEFAULT_SWAP_PARTITION_SIZE"),
    ZOPS_COBBLER_DEFAULT_BOOT_PARTITION_SIZE("ZOPS_COBBLER_DEFAULT_BOOT_PARTITION_SIZE"),
    ZOPS_COBBLER_DEFAULT_UEFI_PARTITION_SIZE("ZOPS_COBBLER_DEFAULT_UEFI_PARTITION_SIZE"),
    ZOPS_COBBLER_MN_KS("ZOPS_COBBLER_MN_KS"),
    ZOPS_COBBLER_NETWORK_IP("ZOPS_COBBLER_NETWORK_IP"),
    ZOPS_COBBLER_SUBNET_RANGE("ZOPS_COBBLER_SUBNET_RANGE"),

    // ansible config
    ZOPS_ANSIBLE_PEX_PATH("ZOPS_ANSIBLE_PEX_PATH"),
    ZOPS_ANSIBLE_TEMP_DIR("ZOPS_ANSIBLE_TEMP_DIR"),

    // zops server config
    ZOPS_UNITEST_MODE("ZOPS_UNITEST_MODE"),
    ZOPS_LOCALE("ZOPS_LOCALE"),
    ZOPS_CONFIG("ZOPS_CONFIG"),
    ZOPS_DISABLED_SYSTEMS("ZOPS_DISABLED_SYSTEMS"),
    ZOPS_SYSTEM_HOME("ZOPS_SYSTEM_HOME"),

    // task worker config
    ZOPS_TASKWORKER_PEX_PATH("ZOPS_TASKWORKER_PEX_PATH"),
}